[package]
name = "ipfs-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ipfs-api-backend-hyper = "0.6"
tokio = {version = "1.41.0", features = ["full"]}
tokio-stream = "0.1.16"
futures = "0.3.31"
uuid = { version = "1.11.0", features = ["v4"] }
